### ISSUE TITLE
Reducing complexity of ipm by delegating tf transformation responsibility to caller

### ISSUE THREAD

**Issue by ijnek** [ros-sports/ipm#12]
Currently, IPM handles cases where the plane's frame_id is different to that of ``output_frame``.
Because of this, IPM must keep track of the transforms using a tfbuffer, which increases complexity.

I think that the transformation can take place outside IPM (delegating responsibilty to the caller of the library or service), and we should assume that the incoming plane and outgoing point are in the same frame.

Is this possible, or am I missing something? What's your thoughts @Flova?

**Comment by ijnek** [comment]
Another benefit would be that we can get rid of PlaneStamped, and just use shape_msgs.msg.Plane

**Comment by Flova** [comment]
We still need a tf_buffer from a purely logical perspective. If we have a given plane like the ground in e.g. the base_footprint frame it needs to be transformed into the camera frame for the projection to work out. We need to consider the relations between the base_footprint and camera frame. This relationship changes over time as e.g. the head moves. The camera frame is also different to the optional output frame, which is used to bring the projected points from the camera frame to a different one, like the base_footprint from the beginning.

We could just implement the projection itself and do everything in the camera frame. But this would move complexity that is needed in nearly every implementation of the ipm to the caller of the library. There is some additional error potential and verbosity on the user side. Most users will have planes that are not located in the camera frame, so a transformation is needed. Even if they are in the same frame tf is smart enough to just directly pass an identity transform which has a low overhead. All of this is independent of the output frame. The projected points are in the camera frame by default. A transformation can be applied to get them back into the output frame which is the plane's frame most of the time. The user could do this by hand later on, but most users will apply this transformation anyway, and it is faster to spare on one message serialization for large point clouds (the transformation is directly applied on the NumPy array without a msg conversion). I think all of this greatly improved the ease of use of the ipm and reduces possible the errors by the user. For example, explicitly defining the planes frame in the plane stamped msg helps with errors where the user might not assume that a plane needs to be generated in the camera frame for each call.

**Comment by ijnek** [comment]
Hmm, so I had a bit of time to think about this. I understand your point, but I also think that the ipm class is doing too much currently.

I original posted this issue suggesting we take all tf stuff completely outside this library, but I think you have changed my mind. It would be good to at least break up the code into two or more classes because ipm has more than one responsibilty currently.

If you agree, I want to keep this issue until we implement the changes.

**Comment by Flova** [comment]
How would you split the IPM class in some way that is easier to understand and has benefits regarding the maintainability? 

We currently do the projection itself using `utils.get_field_intersection_for_pixels` which handles the projection math itself and is in itself stateless. You can use it your self if you want to handle all tf things your self. The IPM class is statefull (holds tf buffer and camera info) and responsible for the ROS/TF side of things. Mainly making sure that the plane is viewed from the right coordinate system at the right time and that the output is also in an expected frame. Both of which are pretty simple, and I don't see where an additional layer might be useful. The IPM class itself is also not that large imo (< 130 loc).

**Comment by ijnek** [comment]
Going to close this, as (at least for now), we're going to proceed with doing the tf inside ipm for ease of use.
