### ISSUE TITLE
Change ``project_point()`` to ``map_point()``

### ISSUE THREAD

**Issue by ijnek** [ros-sports/ipm#14]
This is a suggestion to change the name of the following methods:
* ``project_point()`` to ``map_point()``
* ``project_points()``to ``map_points()``

I believe the correct terminology are as following:

3D -> 2D: Projecting
2D -> 3D: Mapping

```diff
    def project_point(
            self,
            plane: PlaneStamped,
            point: Point,
            output_frame: Optional[str] = None) -> PointStamped:
        """
-       Projects a `Point` onto a given plane using the latest CameraInfo intrinsics.
+       Map 2D `Point` to a 3D `Point` using the latest CameraInfo intrinsics, assuming point lies on given plane.

```

**Comment by Flova** [comment]
Correct me if I am wrong, I also don't have a source on this, but if we compare it to terminology irl it is also a projection. A cinema projector also projects a 2D image onto a 3D plane and not the other way around.

But we could also name it map point as it is more in line with the term inverse perspective mapping.

**Comment by ijnek** [comment]
> Correct me if I am wrong, I also don't have a source on this, but if we compare it to terminology irl it is also a projection. A cinema projector also projects a 2D image onto a 3D plane and not the other way around.

Since I can't find any formal definition after searching, I guess the two terms tend to be used interchangeably.

> But we could also name it map point as it is more in line with the term inverse perspective mapping.

Yes, and it makes the tests where I map the 2d points into 3d coordinates, and project them back into image coordinates easier to read by separating the terminology, so I think I'll proceed with it.
