### ISSUE TITLE
Leverage off vision_opencv/image_geometry?

### ISSUE THREAD

**Issue by ijnek** [ros-sports/ipm#25]
[vision_opencv/image_geometry](https://github.com/ros-perception/vision_opencv/tree/ros2/image_geometry) covers an implementation of ``projectPixelTo3dRay``, similar to what's done in this repo but also handles ROI (also handles binning like we do here).

I'm wondering if there is a way leverage of the work there rather than implementing our own?

There are some obvious issues, like ``projectPixelTo3DRay`` in image_geometry doesn't handle numpy arrays like we can. Could would merge our work into image_geometry so others can benefit from it?

I know there are other things that get in the way too, like my personal opinion of vision_opencv is that it should be refactored, a lot, into better-named packages and non-opencv related things should be taken out of that package.

**Comment by Flova** [comment]
I stumbled upon that a few times in the past. I was mainly stopped by the fact that the math itself isn't that hard to implement, code quality, and that I wanted a fast vectorized implementation.

We could definitely try to bring our implementation upstream in the near future tho..

**Comment by Flova** [comment]
Especially if we consider adding #11, which also exists there, but again only for single points, it might be useful to develop a vectorized version directly for vision_opencv. The vision_opencv python module is btw. written like a cpp dev tried python for once.

**Comment by ijnek** [comment]
I totally agree with your points.

> The vision_opencv python module is btw. written like a cpp dev tried python for once.

:rofl: Yea i posted this issue before I looked into [vision_opencv/image_geometry](https://github.com/ros-perception/vision_opencv/tree/ros2), and despite that package being officially "maintained", it's in a state that I wouldn't want to use until some major improvements are made first.

> Especially if we consider adding #11, which also exists there, but again only for single points, it might be useful to develop a vectorized version directly for vision_opencv.

The rectification stuff was definitely overlapping, I agree. Perhaps we could consider abstracting this out into a separate package like vision_opencv in the future.

Just a summary for reference - although the functionality can be used somewhere more general, for now we'll keep it in this library because there is no other library that provides this functionality reliably and with a fast implementation.
