### ISSUE TITLE
Do we need the launch file?

### ISSUE THREAD

**Issue by ijnek** [ros-sports/ipm#32]
I don't see it much easier:

```sh
# Using launch
ros2 launch ipm_service ipm_service.launch sim:=true

# Using ros2 run
ros2 run ipm_service ipm_service --ros-args -p use_sim_time:=true
```

The second one would be more natural because ``--ros-args -p use_sim_time:=true`` applies for any ROS2 node out there.

If you insist on having the launch file, shouldn't we at least have the parameter name ``use_sim_time`` and not ``sim``? - and at that point, is it still worth the launch file?

> Also, this is future prove as future changes might require launch file features and the "api" is still compatible

I'm not quite sure what you mean here, but I see launch files only useful when you have to start up multiple nodes, or you have more than one set of reasonable parameters for starting a node.

_Originally posted by @ijnek in https://github.com/ros-sports/ipm/pull/5#discussion_r935538773_

**Comment by Flova** [comment]
I made the observation in the past that as components grow they tend to require the features of a launch file, but my opinion is not really strong in this regard. So we can also remove it.

**Comment by ijnek** [comment]
Ok, let's remove and re-add in the future if we have a strong reason that we need it.
