### ISSUE TITLE
New API for ipm_library

### ISSUE THREAD

**Issue by ijnek** [ros-sports/ipm#42]
We discussed in #37 of having a new API as following. Opening this issue so we can keep track of it here instead of the closed PR.

    def map_point(
            self,
            plane: shape_msgs.msg.Plane,
            point: vision_msgs.msg.Point2D,
            time: Time,
            plane_frame_id: Optional[str] = None,  # If None, use the camera frame
            output_frame_id: Optional[str] = None  # If None, use the camera frame) -> PointStamped:

    def map_points(
            self,
            plane: shape_msgs.msg.Plane,
            points: np.ndarray,
            stamp: Time,
            plane_frame_id: Optional[str] = None,  # If None, use the camera frame
            output_frame: Optional[str] = None  # If None, use the camera frame) -> np.ndarray:

_Originally posted by @ijnek in https://github.com/ros-sports/ipm/issues/37#issuecomment-1221249723_

@Flova Could I confirm with you that you were going to work on this?

**Comment by jaagut** [comment]
Is that right, that the variable name for `builtin_interfaces.msg.Time()` is once `time` and `stamp` the other time?

**Comment by ijnek** [comment]
Thanks for picking that up, we should use one or the other for consistency. Let's go with ``time`` unless someone has objections.

**Comment by jaagut** [comment]
It may be a little hypothetical, but `time` could be understood as a point in time or a duration of time.

**Comment by ijnek** [comment]
In general, yes. But luckily, I believe in ROS 2, ``time`` and ``duration`` are quite well defined.

rclcpp/Time.hpp: https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/time.hpp
rclcpp/Duration.hpp: https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/duration.hpp
