### ISSUE TITLE
flake8: import statements are in the wrong order

### ISSUE THREAD

**Issue by ijnek** [ros-sports/ipm#6]
Import orders were juggled around in https://github.com/Flova/ipm/commit/e38d324180e750b7777e80f58976e12b54ad17e6 on Flova:rolling branch to make flake8 happy but I don't really understand why this makes flake8 happy.

From memory, [flake8: import statements are in the wrong order](https://stackoverflow.com/questions/39739118/flake8-import-statements-are-in-the-wrong-order) was the exact issue that arose and the suggested fix in that link says to add a .flake8 file to configure flake8-import-order plugin is needed.

I couldn't get this working, but juggling around the import orders did fix the issue. (And I agree that it looks pretty bad and would like to retain the original order). Would you know much about the fix suggested on StackOverflow......?

_Originally posted by @ijnek in https://github.com/ros-sports/ipm/pull/1#discussion_r830680029_

**Comment by Flova** [comment]
I think that flake8 in ROS seems to want the import statements in alphabetical order independent of `from` or `import`. This also happens here https://github.com/ros2/geometry2/pull/509#pullrequestreview-910813614.

**Comment by ijnek** [comment]
So, the [google style guide is being used by ament_flake8](https://github.com/ament/ament_package/blob/f8ea958fd02cff6f4192425e28566369c92b5e34/.flake8#L3), and here's the import order in [google's documentation](https://google.github.io/styleguide/pyguide.html#313-imports-formatting).

~~It seems like "import" should be used for standard library or third-party modules, while "from * import *" should be used for code repository sub-package imports.~~ THIS WAS WRONG.

**Comment by ijnek** [comment]
Here's an example import file from flake8 (https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_google.py). It seems that google's guide doesn't separate `import` and `from *  import *`, but has them all third party libraries in alphabetical order. 

So although this feels a bit "unusual", that'll be because other projects don't use the google style guide. Feel free to close this if you agree @Flova
